### ISSUE TITLE
User frame number mismatch

### ISSUE THREAD

**Issue by seedship** [gavanderhoorn/fanuc_dpm_mouse_demo#2]
I followed the instructions in the README (Made the corresponding changes to DPM setup and initialized a Server Tag with the SM protocol). I initialized the _cfg by adding assignments during the check like so: https://github.com/seedship/fanuc_dpm_mouse_demo/commit/c12fabaf26f1eb63a470366b15596eeeb4d352ab
but when I run statrackx, I get an invalid uframe number like so:
![issue](https://user-images.githubusercontent.com/885667/76129797-b28fe100-6008-11ea-98b3-39ee2c97b13f.png)

Is my initialization not correct? I'm using server tag S3.

**Comment by gavanderhoorn** [comment]
Line 26 in the TP file is:

https://github.com/gavanderhoorn/fanuc_dpm_mouse_demo/blob/e3dc60661f8e5b152465b93e380765f3cc86430e/statrackx.ls#L47

That position is defined as:

https://github.com/gavanderhoorn/fanuc_dpm_mouse_demo/blob/e3dc60661f8e5b152465b93e380765f3cc86430e/statrackx.ls#L59-L64

It has been recorded with user frame 1.

According to the error manual, `INTP-252` is caused by:

> The user frame number in the positional data is not the same as the currently selected user
frame number.

If you could check your controller for the currently active user frame that would probably show why this error is showing up.

**Comment by gavanderhoorn** [comment]
>  I initialized the _cfg by adding assignments during the check like so: [seedship@c12faba](https://github.com/seedship/fanuc_dpm_mouse_demo/commit/c12fabaf26f1eb63a470366b15596eeeb4d352ab)

this is certainly a valid way to do this, but the idea was to:

 1. `SELECT` the `fdpm_mdemo` Karel program using the TP
 1. go to `DATA`, then change `TYPE` to Karel Vars
 1. navigate to the `cfg_` member, and then
 1. update each of the fields with their correct values

**Comment by seedship** [comment]
Inside FDPM_MDEMO, I added the following lines at the top of BEGIN

```
	$GROUP[1].$UTOOL = $MNUTOOL[1,1] --uTool 1
	$GROUP[1].$UFRAME = $MNUFRAME[1,1] --uFrame 1
```

I even wrote a dedicated program to perform those two assignments and exit, called SET_UFRAME, and ran it before statrackx, but I still got the issue. After I ran SET_UFRAME, this is what I found in user frames. Should it be 1?

![uframe](https://user-images.githubusercontent.com/885667/76146045-c5012d80-608f-11ea-8a5d-223be4b2d142.png)

**Comment by gavanderhoorn** [comment]
> Inside FDPM_MDEMO, I added the following lines at the top of BEGIN
> 
> ```
> 	$GROUP[1].$UTOOL = $MNUTOOL[1,1] --uTool 1
> 	$GROUP[1].$UFRAME = $MNUFRAME[1,1] --uFrame 1
> ```
> 
> I even wrote a dedicated program to perform those two assignments and exit, called SET_UFRAME, and ran it before statrackx, but I still got the issue. 

Why?

It's not the Karel side that causes this error. In fact, there is nothing motion related in the Karel program and `$GROUP[1]` variables do not influence TP motion.

> After I ran SET_UFRAME, this is what I found in user frames. Should it be 1?

From this it would appear you have no user frame active, which could explain this.

Try making the first uframe the active one.

**Comment by seedship** [comment]
Ah, setting the $MNUFRAMENUM[1] = 1 fixed it, thanks!
